FROM node:18.9.1-alpine3.15 as node

WORKDIR /app
COPY . .

WORKDIR /app/frontend

RUN npm install \
    npm run build

FROM python:3.11.1-alpine3.16

WORKDIR /app
COPY --from=node /app/public .
COPY . /app

WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000
ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]